# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AirlineTicketApp', '0002_auto_20170906_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AirlineTicketApp.TypeUser'),
        ),
    ]
