# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 02:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AirlineTicketApp', '0003_auto_20170906_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_class_name', models.SmallIntegerField(choices=[(0, 'Econnomy'), (1, 'Premium Economy'), (2, 'Business')])),
                ('seat_class_price', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AirlineTicketApp.Flight')),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type_name', models.SmallIntegerField(choices=[(0, 'Adults'), (1, 'Childrent'), (2, 'Baby')])),
                ('ticket_type_price', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='TypeUser',
            new_name='UserType',
        ),
        migrations.RemoveField(
            model_name='book',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.RenameField(
            model_name='airline',
            old_name='price_airline',
            new_name='airline_price',
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='address_airport',
            new_name='airport_address',
        ),
        migrations.RenameField(
            model_name='bookinfo',
            old_name='number_seat',
            new_name='seat_number',
        ),
        migrations.RenameField(
            model_name='bookinfo',
            old_name='price_ticket_book',
            new_name='ticket_book_price',
        ),
        migrations.RenameField(
            model_name='plane',
            old_name='numbers_gate',
            new_name='gate_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='type_user',
            new_name='user_type',
        ),
        migrations.RenameField(
            model_name='usertype',
            old_name='type_user_name',
            new_name='user_type_name',
        ),
        migrations.RemoveField(
            model_name='bookinfo',
            name='type_seat',
        ),
        migrations.RemoveField(
            model_name='bookinfo',
            name='type_ticket',
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AirlineTicketApp.TicketBook'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='TypeSeat',
        ),
        migrations.DeleteModel(
            name='TypeTicket',
        ),
        migrations.AddField(
            model_name='ticketbook',
            name='user',
            field=models.ForeignKey(help_text='Khách Hàng', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='seat_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AirlineTicketApp.SeatType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='ticket_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AirlineTicketApp.TicketType'),
            preserve_default=False,
        ),
    ]
